
// DO NOT EDIT THIS FILE. GENERATED BY mkdoc.sh.
// Edit the documentation in other files and rerun mkdoc.sh to generate this one.

/*
Aonui is a tool for downloading and managing meteorological data.

Usage:

        aonui command [arguments]

The commands are:

    sync        fetch wind data from the GFS
    inv         filter and sort GRIB2 inventories into Tawhiri order
    reorder     re-order a GRIB2 file into Tawhiri order
    extract     extract binary data from a GRIB2 message into Tawhiri order

Use "aonui help [command]" for more information about a command.

Additional help topics:

    tawhiri     the Tawhiri data ordering

Use "aonui help [topic]" for more information about that topic.


Fetch wind data from the GFS

Usage:

        aonui sync [-basedir directory] [-highres] [-maxruns number]

Sync will fetch wind data from the Global Forecast System (GFS) servers in
GRIB2 data. It will only fetch the subset of the data needed. It knows how to
fetch both the current 0.5 degree resolution data and the forthcoming 0.25
degree data.

Data is saved to the file gfs.YYYMMDDHH.grib2 where YYYY, MM, DD and HH are the
year, month, day and hour of the run with an appropriate number of leading
zeros.

The -basedir option specifies the directory data should be downloaded to. If
omitted, the current working directory is used.

If the -highres option is present, 0.25 degree data will be downloaded. If
omitted, the 0.5 degree data is downloaded.

The -maxruns options controls how far into the past sync will look for data
before stopping. The default value of 3 means examine the 3 newest runs on the
server starting with the newest. If any run is a) incomplete on the server or
b) already downloaded proceed to the next until the list of runs is exhausted.

The utility attempts to be robust in the face of flaky network connections or a
flaky server by re-trying failed downloads.


Filter and sort GRIB2 inventories into Tawhiri order

Usage:

        aonui inv [-nosort] [-nofilter] gribfile

Inv dumps and optionally filters and sorts a GRIB2's inventory into the order
Tawhiri expects. (See "aonui help tawhiri" for details on this ordering.)

The first time this command is run on a file it can take a long time to
generate output as wgrib2 will need to scan through the entire GRIB2 message.

Inv does not directly deal with latitudes or longitudes but will parse the
inventory from the specified GRIB2 file and output an inventory on standard
output which corresponds to the Tawhiri ordering for parameters, pressures and
forecast hours.

Inv will sort inventory items as described above but this behaviour may be
disabled via the -nosort flag.

Inv will remove inventory items not used by Tawhiri. This behaviour can be
disabled via the -nofilter flag. In this case non-Tawhiri inventory
items will be sorted after Tawhiri ones.

With -nosort and -nofilter both enabled, inv should generate an inventory
identical to that produced by "wgrib2 -s".

See also: aonui help tawhiri


Re-order a GRIB2 file into Tawhiri order

Usage:

        aonui reorder ingribfile outgribfile

Reorder will take an existing GRIB2 file on disk and write out a new GRIB2 file
with the records re-ordered into the order Tawhiri expects. (See "aonui help
tawhiri" for details on this ordering.)

Input is read from ingribfile and written to outgribfile. Records not used by
Tawhiri will not be written to the output.

See also: aonui help tawhiri


Extract binary data from a GRIB2 message into Tawhiri order

Usage:

        aonui extract <ingrib> <outbin>

Extract will parse a GRIB2 message in the file ingrib and write a raw binary
dump of native-endian floating point values to outbin in Tawhiri order.

See also: aonui help tawhiri


The Tawhiri data ordering

The Tawhiri predictor treats the wind data as a large five-dimensional array of
floating point values in a particular order.

The data should be ordered into a C-style array with dimensions forecast hour,
pressure, parameter, latitude and longitude. "C-style" here meaning that
adjacent records in the file correspond to changes in longitude.

Longitudes are ordered West-to-East and latitudes are ordered South-to-North.
Parameters are in the order HGT, UGRD, VGRD.  Pressures are in decreasing
numerical order. (This is so that the first pressure corresponds to the lowest
geo-potential height.) Forecast hours are in increasing numerical order.


*/
package main
